//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzFileTransfer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFiles", ReplyAction="http://tempuri.org/IService1/GetAllFilesResponse")]
        AzFileTransfer.ServiceReference1.GetAllFilesResponse GetAllFiles(AzFileTransfer.ServiceReference1.GetAllFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFiles", ReplyAction="http://tempuri.org/IService1/GetAllFilesResponse")]
        System.Threading.Tasks.Task<AzFileTransfer.ServiceReference1.GetAllFilesResponse> GetAllFilesAsync(AzFileTransfer.ServiceReference1.GetAllFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadStream", ReplyAction="http://tempuri.org/IService1/DownloadStreamResponse")]
        AzFileTransfer.ServiceReference1.DownloadStreamResponse DownloadStream(AzFileTransfer.ServiceReference1.DownloadStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadStream", ReplyAction="http://tempuri.org/IService1/DownloadStreamResponse")]
        System.Threading.Tasks.Task<AzFileTransfer.ServiceReference1.DownloadStreamResponse> DownloadStreamAsync(AzFileTransfer.ServiceReference1.DownloadStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadFile", ReplyAction="http://tempuri.org/IService1/UploadFileResponse")]
        AzFileTransfer.ServiceReference1.UploadFileResponse UploadFile(AzFileTransfer.ServiceReference1.FileUploadMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadFile", ReplyAction="http://tempuri.org/IService1/UploadFileResponse")]
        System.Threading.Tasks.Task<AzFileTransfer.ServiceReference1.UploadFileResponse> UploadFileAsync(AzFileTransfer.ServiceReference1.FileUploadMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownLoadFile", ReplyAction="http://tempuri.org/IService1/DownLoadFileResponse")]
        AzFileTransfer.ServiceReference1.FileDownLoadMessage DownLoadFile(AzFileTransfer.ServiceReference1.FileDownLoadMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownLoadFile", ReplyAction="http://tempuri.org/IService1/DownLoadFileResponse")]
        System.Threading.Tasks.Task<AzFileTransfer.ServiceReference1.FileDownLoadMessage> DownLoadFileAsync(AzFileTransfer.ServiceReference1.FileDownLoadMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllFilesRequest {
        
        public GetAllFilesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.FileInfo[] GetAllFilesResult;
        
        public GetAllFilesResponse() {
        }
        
        public GetAllFilesResponse(System.IO.FileInfo[] GetAllFilesResult) {
            this.GetAllFilesResult = GetAllFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadStream", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.FileInfo fileinfo;
        
        public DownloadStreamRequest() {
        }
        
        public DownloadStreamRequest(System.IO.FileInfo fileinfo) {
            this.fileinfo = fileinfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadStreamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream DownloadStreamResult;
        
        public DownloadStreamResponse() {
        }
        
        public DownloadStreamResponse(System.IO.Stream DownloadStreamResult) {
            this.DownloadStreamResult = DownloadStreamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long CurrentFileSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long TotalFileSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] FileData;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(long CurrentFileSize, string FileName, long TotalFileSize, byte[] FileData) {
            this.CurrentFileSize = CurrentFileSize;
            this.FileName = FileName;
            this.TotalFileSize = TotalFileSize;
            this.FileData = FileData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileDownLoadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileDownLoadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.IO.FileInfo fiFileInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long lFileSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long lOffset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] abtFileData;
        
        public FileDownLoadMessage() {
        }
        
        public FileDownLoadMessage(System.IO.FileInfo fiFileInfo, long lFileSize, long lOffset, byte[] abtFileData) {
            this.fiFileInfo = fiFileInfo;
            this.lFileSize = lFileSize;
            this.lOffset = lOffset;
            this.abtFileData = abtFileData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AzFileTransfer.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AzFileTransfer.ServiceReference1.IService1>, AzFileTransfer.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AzFileTransfer.ServiceReference1.GetAllFilesResponse GetAllFiles(AzFileTransfer.ServiceReference1.GetAllFilesRequest request) {
            return base.Channel.GetAllFiles(request);
        }
        
        public System.Threading.Tasks.Task<AzFileTransfer.ServiceReference1.GetAllFilesResponse> GetAllFilesAsync(AzFileTransfer.ServiceReference1.GetAllFilesRequest request) {
            return base.Channel.GetAllFilesAsync(request);
        }
        
        public AzFileTransfer.ServiceReference1.DownloadStreamResponse DownloadStream(AzFileTransfer.ServiceReference1.DownloadStreamRequest request) {
            return base.Channel.DownloadStream(request);
        }
        
        public System.Threading.Tasks.Task<AzFileTransfer.ServiceReference1.DownloadStreamResponse> DownloadStreamAsync(AzFileTransfer.ServiceReference1.DownloadStreamRequest request) {
            return base.Channel.DownloadStreamAsync(request);
        }
        
        public AzFileTransfer.ServiceReference1.UploadFileResponse UploadFile(AzFileTransfer.ServiceReference1.FileUploadMessage request) {
            return base.Channel.UploadFile(request);
        }
        
        public System.Threading.Tasks.Task<AzFileTransfer.ServiceReference1.UploadFileResponse> UploadFileAsync(AzFileTransfer.ServiceReference1.FileUploadMessage request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public AzFileTransfer.ServiceReference1.FileDownLoadMessage DownLoadFile(AzFileTransfer.ServiceReference1.FileDownLoadMessage request) {
            return base.Channel.DownLoadFile(request);
        }
        
        public System.Threading.Tasks.Task<AzFileTransfer.ServiceReference1.FileDownLoadMessage> DownLoadFileAsync(AzFileTransfer.ServiceReference1.FileDownLoadMessage request) {
            return base.Channel.DownLoadFileAsync(request);
        }
    }
}
